steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'eu.gcr.io/tes-wes/taskmaster:dev-latest', '-f', 'dockerfiles/taskmaster/Dockerfile', '.']
images: ['eu.gcr.io/tes-wes/taskmaster:dev-latest']
